components:
  gmmlib:
    dest_dir: gmmlib
    type: git
    branch: gmmlib
    revision: intel-gmmlib-19.4.1
    repository: https://github.com/intel/gmmlib.git
  igc:
    dest_dir: igc
    type: git
    branch: igc
    revision: b25b5ebe8b4dd0a36a776250dff7bd9a21b613c6
    repository: https://github.com/intel/intelgraphicscompiler
  infra:
    branch: infra
    dest_dir: infra
    revision: d21b9c3b0f782856c41f775467f518a41d80be1c
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: 1c2431fee90cdd30f4cabba11aa5d048af80c94d
    type: git
  kmdaf:
    branch: kmdaf
    dest_dir: kmdaf
    revision: 710b620b08792ba0367bcabd54c479ede7518603
    type: git
  libva:
    dest_dir: libva
    type: git
    branch: libva
    revision: c9bb65b
    repository: https://github.com/intel/libva.git
  wdk:
    dest_dir: wdk
    type: git
    branch: wdk
    revision: 39ec79c0ca347796daa7b07fbb81dd1bf45ccad5-1355
converter: M-1371
version: '1'
