components:
  gmmlib:
    branch: gmmlib
    clean_on_sync: true
    dest_dir: gmmlib
    repository: https://github.com/intel/gmmlib.git
    revision: 3f3138424bb21ebf5de105226b85630f4f69dbf6
    type: git
  igc:
    branch: igc
    clean_on_sync: true
    dest_dir: igc
    repository: https://github.com/intel/intelgraphicscompiler
    revision: 65bbbe3ea8afb2d40ef759a51a358b4795860ce0
    type: git
  infra:
    branch: infra
    clean_on_sync: true
    dest_dir: infra
    revision: 8abea2b4f36cb427643575a3127ea3c9c8c157d5
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: 66b31e46172f33de0430bae58e01471670991f0f
    type: git
  khronos:
    branch: master
    clean_on_sync: true
    dest_dir: khronos
    repository: https://github.com/KhronosGroup/OpenCL-Headers.git
    revision: de26592167b9fdea503885e40e8755393c56523d
    type: git
  kmdaf:
    branch: kmdaf
    clean_on_sync: true
    dest_dir: kmdaf
    revision: 99402337f2b42a058a1b20cb0dc130033fdbd65f
    type: git
  wdk:
    branch: wdk
    clean_on_sync: true
    dest_dir: wdk
    revision: 769497-961
    type: git
converter: M-962
version: '1'
