components:
  gmmlib:
    branch: gmmlib
    clean_on_sync: true
    dest_dir: gmmlib
    repository: https://github.com/intel/gmmlib.git
    revision: intel-gmmlib-19.2.3
    type: git
  igc:
    branch: igc
    clean_on_sync: true
    dest_dir: igc
    repository: https://github.com/intel/intelgraphicscompiler
    revision: 01ca219b145d40e77e74a694ea79bcaf629416b6
    type: git
  infra:
    branch: infra
    clean_on_sync: true
    dest_dir: infra
    revision: 507920aa8d3242c4d17ba3b682725624a5fe02c9
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: 84c3bc102160ea8337ddb776e0e51806c2867727
    type: git
  kmdaf:
    branch: kmdaf
    clean_on_sync: true
    dest_dir: kmdaf
    revision: 117d709602a49f4aae6e7965743cec61834a3c35
    type: git
  libva:
    branch: libva
    clean_on_sync: true
    dest_dir: libva
    repository: https://github.com/intel/libva.git
    revision: c9bb65b
    type: git
  wdk:
    branch: wdk
    clean_on_sync: true
    dest_dir: wdk
    revision: 4e7310ad4b14ce24a1fa8a048619590454d57619-1293
    type: git
converter: M-1293
version: '1'
