components:
  gmmlib:
    dest_dir: gmmlib
    type: git
    branch: gmmlib
    revision: intel-gmmlib-19.4.1
    repository: https://github.com/intel/gmmlib.git
  igc:
    dest_dir: igc
    type: git
    branch: igc
    revision: 8a1f2c37ee213e91d73fa734d19ca864ebed0ba9
    repository: https://github.com/intel/intelgraphicscompiler
  infra:
    branch: infra
    dest_dir: infra
    revision: b64b9ba31f888cfc3e13dbcaf5218bd150ea9612
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: 4a734796a9d568a8b53fddba7b66bdc72b22a833
    type: git
  kmdaf:
    branch: kmdaf
    dest_dir: kmdaf
    revision: 710b620b08792ba0367bcabd54c479ede7518603
    type: git
  libva:
    dest_dir: libva
    type: git
    branch: libva
    revision: c9bb65b
    repository: https://github.com/intel/libva.git
  wdk:
    dest_dir: wdk
    type: git
    branch: wdk
    revision: 39ec79c0ca347796daa7b07fbb81dd1bf45ccad5-1355
converter: M-1371
version: '1'
