components:
  gmmlib:
    branch: gmmlib
    clean_on_sync: true
    dest_dir: gmmlib
    repository: https://github.com/intel/gmmlib.git
    revision: intel-gmmlib-19.2.3
    type: git
  igc:
    branch: igc
    clean_on_sync: true
    dest_dir: igc
    repository: https://github.com/intel/intelgraphicscompiler
    revision: 6dd3bde8f93ee61f798f84a34a9c9e66d0aedd49
    type: git
  infra:
    branch: infra
    clean_on_sync: true
    dest_dir: infra
    revision: 256b28fe7ce0e5eda33367c9c076d28c7c575930
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: 08cd02e12efcf12aec4abefe77f577c82f004583
    type: git
  kmdaf:
    branch: kmdaf
    clean_on_sync: true
    dest_dir: kmdaf
    revision: 117d709602a49f4aae6e7965743cec61834a3c35
    type: git
  libva:
    branch: libva
    clean_on_sync: true
    dest_dir: libva
    repository: https://github.com/intel/libva.git
    revision: c9bb65b
    type: git
  wdk:
    branch: wdk
    clean_on_sync: true
    dest_dir: wdk
    revision: 4e7310ad4b14ce24a1fa8a048619590454d57619-1293
    type: git
converter: M-1304
version: '1'
