components:
  gmmlib:
    clean_on_sync: true
    dest_dir: gmmlib
    type: git
    branch: gmmlib
    revision: intel-gmmlib-19.3.2
    repository: https://github.com/intel/gmmlib.git
  igc:
    clean_on_sync: true
    dest_dir: igc
    type: git
    branch: igc
    revision: igc-1.0.2714.1
    repository: https://github.com/intel/intelgraphicscompiler
  infra:
    branch: infra
    clean_on_sync: true
    dest_dir: infra
    revision: ec6c89b569c7434f13a109a37e62d6e8c5f8b9c4
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: 67ff035d52a3759ec2352ced17673b25c47ebbe0
    type: git
  kmdaf:
    branch: kmdaf
    clean_on_sync: true
    dest_dir: kmdaf
    revision: 117d709602a49f4aae6e7965743cec61834a3c35
    type: git
  libva:
    clean_on_sync: true
    dest_dir: libva
    type: git
    branch: libva
    revision: c9bb65b
    repository: https://github.com/intel/libva.git
  wdk:
    clean_on_sync: true
    dest_dir: wdk
    type: git
    branch: wdk
    revision: 682c4e3d433c6796acebfcbc8f0e2a5135f58412-1330
converter: M-1330
version: '1'
