components:
  gmmlib:
    branch: gmmlib
    clean_on_sync: true
    dest_dir: gmmlib
    repository: https://github.com/intel/gmmlib.git
    revision: 5ff84b923ec2ba1572c464dc8def73348571b440
    type: git
  igc:
    branch: igc
    clean_on_sync: true
    dest_dir: igc
    repository: https://github.com/intel/intelgraphicscompiler
    revision: dca01ed360be2cdcaad1ce422e84edd0cbdb6a92
    type: git
  infra:
    branch: infra
    clean_on_sync: true
    dest_dir: infra
    revision: 9912b9be69726cf6bbb2837318da8767b4263f60
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: 2a7a6dcaf492b1c12edca1867e3adca9b771a929
    type: git
  kmdaf:
    branch: kmdaf
    clean_on_sync: true
    dest_dir: kmdaf
    revision: 99402337f2b42a058a1b20cb0dc130033fdbd65f
    type: git
  wdk:
    branch: wdk
    clean_on_sync: true
    dest_dir: wdk
    revision: 769497-961
    type: git
converter: M-963
version: '1'
