components:
  gmmlib:
    branch: gmmlib
    clean_on_sync: true
    dest_dir: gmmlib
    repository: https://github.com/intel/gmmlib.git
    revision: intel-gmmlib-18.4.1
    type: git
  igc:
    branch: igc
    clean_on_sync: true
    dest_dir: igc
    repository: https://github.com/intel/intelgraphicscompiler
    revision: fb7c719ae745744e0308d2cfb430d39672e9a879
    type: git
  infra:
    branch: infra
    clean_on_sync: true
    dest_dir: infra
    revision: 296228f0dec47a480e473f941ff57b7ea3231779
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: 004c53f38a5280e4007e2f2ff2e76f3ac7d32adc
    type: git
  kmdaf:
    branch: kmdaf
    clean_on_sync: true
    dest_dir: kmdaf
    revision: 3e45a728e94ee8ed0faa968d22409ac1465bcb60
    type: git
  libva:
    branch: libva
    clean_on_sync: true
    dest_dir: libva
    repository: https://github.com/intel/libva.git
    revision: c9bb65b
    type: git
  wdk:
    branch: wdk
    clean_on_sync: true
    dest_dir: wdk
    revision: 490656085824efd6e1d9745aa2e149ebd97fb8dc-1213
    type: git
converter: M-1215
version: '1'
