components:
  gmmlib:
    clean_on_sync: true
    dest_dir: gmmlib
    type: git
    branch: gmmlib
    revision: intel-gmmlib-19.3.2
    repository: https://github.com/intel/gmmlib.git
  igc:
    clean_on_sync: true
    dest_dir: igc
    type: git
    branch: igc
    revision: b3ed5e584dac45d560e6f68e5f6e84af8a661e6e
    repository: https://github.com/intel/intelgraphicscompiler
  infra:
    branch: infra
    clean_on_sync: true
    dest_dir: infra
    revision: a152d6f19efd614d90bcbf0cea38be50a26313c4
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: 48d63ccbc1d35ade6d369f7c7221dc545ad8a913
    type: git
  kmdaf:
    branch: kmdaf
    clean_on_sync: true
    dest_dir: kmdaf
    revision: 117d709602a49f4aae6e7965743cec61834a3c35
    type: git
  libva:
    clean_on_sync: true
    dest_dir: libva
    type: git
    branch: libva
    revision: c9bb65b
    repository: https://github.com/intel/libva.git
  wdk:
    clean_on_sync: true
    dest_dir: wdk
    type: git
    branch: wdk
    revision: 8be1d76981dd74c7230ea948a72559678d1850ec-1311
converter: M-1311
version: '1'
