components:
  gmmlib:
    dest_dir: gmmlib
    type: git
    branch: gmmlib
    revision: intel-gmmlib-19.4.1
    repository: https://github.com/intel/gmmlib.git
  igc:
    dest_dir: igc
    type: git
    branch: igc
    revision: 206632b8ebaabc3ffcdfeb76a184a913ff2a4d77
    repository: https://github.com/intel/intelgraphicscompiler
  infra:
    branch: infra
    dest_dir: infra
    revision: c0676b1b2eebded32d1c49a1545e096534012a5d
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: c51a016e179e0f2cd69758650612836c417306c9
    type: git
  kmdaf:
    branch: kmdaf
    dest_dir: kmdaf
    revision: 710b620b08792ba0367bcabd54c479ede7518603
    type: git
  libva:
    dest_dir: libva
    type: git
    branch: libva
    revision: c9bb65b
    repository: https://github.com/intel/libva.git
  wdk:
    dest_dir: wdk
    type: git
    branch: wdk
    revision: 39ec79c0ca347796daa7b07fbb81dd1bf45ccad5-1355
converter: M-1371
version: '1'
